get_power_data:
  name: "Get Power Data from iDRAC"
  description: "Fetches the latest power consumption data from Dell iDRAC."
  fields:
    force_update:
      description: "Force an immediate update (true/false)."
      example: "true"

set_price_per_kwh:
  name: "Set Price Per kWh"
  description: "Updates the electricity cost per kWh for calculations."
  fields:
    price:
      description: "New price per kWh in your local currency."
      example: "0.75"